DjangoNews/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('markdownx/', include('markdownx.urls')),
    path('', include('news.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns + static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

news/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('articles/', views.ArticleListView.as_view(), name='articles'),
    path('article/<int:pk>/', views.ArticleDetailView.as_view(), name='article'),
    path('reporter/<str:username>/', views.reporter, name='reporter'),
]

news/models.py
from django.db import models
from django.contrib.auth.models import User
from markdownx.models import MarkdownxField

def get_deleted_user():
    return User.objects.get_or_create(username="ghost")[0]

class Article(models.Model):
    headline = models.CharField(max_length=255)
    short_desc = models.CharField(max_length=255, verbose_name="Short Description")
    content = MarkdownxField()
    pub_on = models.DateTimeField(auto_now_add=True, verbose_name="Published On")
    reporter = models.ForeignKey(User, on_delete=models.SET(get_deleted_user))

    def __str__(self):
        return self.headline

    def get_absolute_url(self):
        from django.urls import reverse
        return reverse('article', kwargs={'pk': self.pk})

news/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.views.generic import *
from django.contrib.auth.models import User

from .models import Article

def home(request):
    return redirect('articles')



class ArticleListView(ListView):
    model = Article
    context_object_name = "articles"


class ArticleDetailView(DetailView):
    model = Article
    context_obejct_name = "article"


def reporter(request, username):
    reporter = get_object_or_404(User, username=username)
    context = {
        'reporter': reporter
    }
    return render(request, 'news/reporter.html', context)

news/templates/news/Article_detail.html
{% extends 'base.html' %}
{% load markdownify %}

{% block title %}
    {{article.headline}}
{% endblock title %}
    

{% block content %}
    <div class="container">
        <div class="jumbotron">
            <h1 class="display-4">{{ article.headline }}</h1>
            <p class="lead">{{ article.short_desc }}</p>
            <hr class="my-4">
            {{article.content | markdownify}}
            <br>
            <br>
            <a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a>
          </div>
    </div>
{% endblock content %}
    

news/templates/news/Article_list.html
{% extends 'base.html' %}
{% load humanize %}
{% block title %}
    Articles
{% endblock title %}
    

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-8 blog-main">
        <h3 class="pb-4 mb-4 font-italic border-bottom">
            From the Server
          </h3>
        <ul class="list-group list-group-flush">
            
            {% for article in articles %}
            <div class="blog-post">
                <h2 class="blog-post-title"><a href="{% url 'article' article.pk %}">{{ article.headline }}</a></h2>
                <p class="blog-post-meta">{{ article.pub_on | naturaltime }} by <a href="{% url 'reporter' article.reporter.username %}">@{{ article.reporter.get_username | title }}</a></p>
        
                <p>{{ article.short_desc }}</p>
            </div>
            {% endfor %}
                
        </ul>
    </div>
{% endblock content %}
    

news/templates/news/reporter.html
{% extends 'base.html' %}
{% load humanize %}
{% block title %}
    {{reporter.get_username | title}}
{% endblock title %}
    

{% block content %}
    <div class="container">
        <div class="jumbotron">
            <h1 class="display-4">{{ reporter.get_username | title }}</h1>
            <p class="lead">{{ reporter.get_full_name | title }}</p>
            <p class="lead">Joined: {{ reporter.date_joined | naturaltime }}</p>
            <p class="lead">Email: <a href="mailto:{{reporter.email}}">{{ reporter.email }}</a></p>          
          </div>
          <ul class="list-group list-group-flush">
                
            {% for article in reporter.article_set.all %}
            <li class="list-group-item"><a href="{% url 'article' article.pk %}">{{article.headline}}</a></li>
            {% endfor %}
                
        </ul>
    </div>
{% endblock content %}
    